### ISSUE TITLE
Color Bolck 1.16.3/ Color tool

### ISSUE THREAD

**Issue by MoreOre-Team** [Silverminer007/Color-Block-Mod#4]
das Color Tool nimmt die Farbe auf aber gibt sie nicht an einen andern Color Block weiter. 
[crash-2020-09-19_11.59.36-client.txt](https://github.com/Silverminer007/Color-Block-Mod/files/5249597/crash-2020-09-19_11.59.36-client.txt)
[latest.log](https://github.com/Silverminer007/Color-Block-Mod/files/5249604/latest.log)
[debug.log](https://github.com/Silverminer007/Color-Block-Mod/files/5249608/debug.log)

**Comment by Silverminer007** [comment]
The Bug is fixed in realse color_block-1.16.3-1.4.0-Beta7
